dist: trusty
language: node_js

node_js:
  - 8

script:
  - npm run ci

after_script:
  - ./node_modules/.bin/codecov
  - node ./scripts/uploadCodeCov.js

deploy:
  provider: script
  script: "gem install compass && npm run docs"
  skip_cleanup: true
  on:
    tags: true
